server:
  port: 8080
logging:
  level:
    com.ll.todo20231222: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO
custom:
  site:
    cookieDomain: "${custom.production.cookieDomain}"
    frontUrl: "${custom.production.frontUrl}"
    backUrl: "${custom.production.backUrl}"